[package]
name = "mcts-connect-four-bin"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
connect-four-logic = { path = "../../lib/game/connect-four-logic" }
mcts-connect-four = { path = "../../lib/end-to-end/mcts-connect-four" }
monte-carlo-tree-search = { path = "../../lib/book/monte-carlo-tree-search" }
rand = "0.8.5"
rand_pcg = "0.3.1"
rayon = "1.6.1"
serde = "1.0.152"

[dev-dependencies]
proptest = "1.1.0"
