[package]
name = "mcts-connect-four"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
connect-four = { path = "../../lib/connect-four" }
monte-carlo-tree-search = { path = "../../lib/monte-carlo-tree-search" }
proptest = "1.1.0"
rand = "0.8.5"
rand_pcg = "0.3.1"
rayon = "1.6.1"
serde = "1.0.152"

[dependencies.snmalloc-rs]
version = "0.3.3"
features = ["native-cpu"]
