[package]
name = "vacuum-agents"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vacuum-cleaner = { path = "../../lib/vacuum-cleaner" }